import type { Metadata } from "next";
import { Almarai,Fustat} from "next/font/google";
import "./globals.css";

const almarai = Almarai({
  subsets: ["arabic"],
  weight: ["300", "400", "700"],
  variable: "--font-almarai",
  display: "swap",
});

const fustat = Fustat({
  subsets: ["arabic"],
  weight: ["300", "400", "700"],
  variable: "--font-fustat",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body
        className={`${almarai.variable} ${fustat.variable} almarai-regular`}
      >
        {children}
      </body>
    </html>
  );
}
